//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SofaSurgical
{
    [Serializable]
    public class DeformationUpdateMsg : Message
    {
        public const string k_RosMessageName = "sofa_surgical_msgs/DeformationUpdate";
        public override string RosMessageName => k_RosMessageName;

        //  DeformationUpdate.msg
        public string node_name;
        public int[] vertex_ids;
        public DisplacementMsg[] displacements;
        public double timestamp;

        public DeformationUpdateMsg()
        {
            this.node_name = "";
            this.vertex_ids = new int[0];
            this.displacements = new DisplacementMsg[0];
            this.timestamp = 0.0;
        }

        public DeformationUpdateMsg(string node_name, int[] vertex_ids, DisplacementMsg[] displacements, double timestamp)
        {
            this.node_name = node_name;
            this.vertex_ids = vertex_ids;
            this.displacements = displacements;
            this.timestamp = timestamp;
        }

        public static DeformationUpdateMsg Deserialize(MessageDeserializer deserializer) => new DeformationUpdateMsg(deserializer);

        private DeformationUpdateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node_name);
            deserializer.Read(out this.vertex_ids, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.displacements, DisplacementMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.timestamp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node_name);
            serializer.WriteLength(this.vertex_ids);
            serializer.Write(this.vertex_ids);
            serializer.WriteLength(this.displacements);
            serializer.Write(this.displacements);
            serializer.Write(this.timestamp);
        }

        public override string ToString()
        {
            return "DeformationUpdateMsg: " +
            "\nnode_name: " + node_name.ToString() +
            "\nvertex_ids: " + System.String.Join(", ", vertex_ids.ToList()) +
            "\ndisplacements: " + System.String.Join(", ", displacements.ToList()) +
            "\ntimestamp: " + timestamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
