//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SofaSurgical
{
    [Serializable]
    public class DisplacementMsg : Message
    {
        public const string k_RosMessageName = "sofa_surgical_msgs/Displacement";
        public override string RosMessageName => k_RosMessageName;

        //  Displacement.msg
        public double dx;
        public double dy;
        public double dz;

        public DisplacementMsg()
        {
            this.dx = 0.0;
            this.dy = 0.0;
            this.dz = 0.0;
        }

        public DisplacementMsg(double dx, double dy, double dz)
        {
            this.dx = dx;
            this.dy = dy;
            this.dz = dz;
        }

        public static DisplacementMsg Deserialize(MessageDeserializer deserializer) => new DisplacementMsg(deserializer);

        private DisplacementMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dx);
            deserializer.Read(out this.dy);
            deserializer.Read(out this.dz);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dx);
            serializer.Write(this.dy);
            serializer.Write(this.dz);
        }

        public override string ToString()
        {
            return "DisplacementMsg: " +
            "\ndx: " + dx.ToString() +
            "\ndy: " + dy.ToString() +
            "\ndz: " + dz.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
