//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SofaSurgical
{
    [Serializable]
    public class TetrahedronMsg : Message
    {
        public const string k_RosMessageName = "sofa_surgical_msgs/Tetrahedron";
        public override string RosMessageName => k_RosMessageName;

        //  Tetrahedron.msg
        public int[] vertices_indices;

        public TetrahedronMsg()
        {
            this.vertices_indices = new int[4];
        }

        public TetrahedronMsg(int[] vertices_indices)
        {
            this.vertices_indices = vertices_indices;
        }

        public static TetrahedronMsg Deserialize(MessageDeserializer deserializer) => new TetrahedronMsg(deserializer);

        private TetrahedronMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vertices_indices, sizeof(int), 4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vertices_indices);
        }

        public override string ToString()
        {
            return "TetrahedronMsg: " +
            "\nvertices_indices: " + System.String.Join(", ", vertices_indices.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
