//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EcmController
{
    [Serializable]
    public class PatientMeshArrayMsg : Message
    {
        public const string k_RosMessageName = "ecm_controller/PatientMeshArray";
        public override string RosMessageName => k_RosMessageName;

        public PatientMeshMsg[] mesh_obstacles;

        public PatientMeshArrayMsg()
        {
            this.mesh_obstacles = new PatientMeshMsg[0];
        }

        public PatientMeshArrayMsg(PatientMeshMsg[] mesh_obstacles)
        {
            this.mesh_obstacles = mesh_obstacles;
        }

        public static PatientMeshArrayMsg Deserialize(MessageDeserializer deserializer) => new PatientMeshArrayMsg(deserializer);

        private PatientMeshArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mesh_obstacles, PatientMeshMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.mesh_obstacles);
            serializer.Write(this.mesh_obstacles);
        }

        public override string ToString()
        {
            return "PatientMeshArrayMsg: " +
            "\nmesh_obstacles: " + System.String.Join(", ", mesh_obstacles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
