//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.EcmController
{
    [Serializable]
    public class PatientMeshMsg : Message
    {
        public const string k_RosMessageName = "ecm_controller/PatientMesh";
        public override string RosMessageName => k_RosMessageName;

        public string patient_id;
        public Shape.MeshMsg reconstructed_mesh;
        public Geometry.PoseMsg mesh_pose;

        public PatientMeshMsg()
        {
            this.patient_id = "";
            this.reconstructed_mesh = new Shape.MeshMsg();
            this.mesh_pose = new Geometry.PoseMsg();
        }

        public PatientMeshMsg(string patient_id, Shape.MeshMsg reconstructed_mesh, Geometry.PoseMsg mesh_pose)
        {
            this.patient_id = patient_id;
            this.reconstructed_mesh = reconstructed_mesh;
            this.mesh_pose = mesh_pose;
        }

        public static PatientMeshMsg Deserialize(MessageDeserializer deserializer) => new PatientMeshMsg(deserializer);

        private PatientMeshMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.patient_id);
            this.reconstructed_mesh = Shape.MeshMsg.Deserialize(deserializer);
            this.mesh_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.patient_id);
            serializer.Write(this.reconstructed_mesh);
            serializer.Write(this.mesh_pose);
        }

        public override string ToString()
        {
            return "PatientMeshMsg: " +
            "\npatient_id: " + patient_id.ToString() +
            "\nreconstructed_mesh: " + reconstructed_mesh.ToString() +
            "\nmesh_pose: " + mesh_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
