//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SofaSurgical
{
    [Serializable]
    public class GetOrganResponse : Message
    {
        public const string k_RosMessageName = "sofa_surgical_msgs/GetOrgan";
        public override string RosMessageName => k_RosMessageName;

        public OrganMsg organ;

        public GetOrganResponse()
        {
            this.organ = new OrganMsg();
        }

        public GetOrganResponse(OrganMsg organ)
        {
            this.organ = organ;
        }

        public static GetOrganResponse Deserialize(MessageDeserializer deserializer) => new GetOrganResponse(deserializer);

        private GetOrganResponse(MessageDeserializer deserializer)
        {
            this.organ = OrganMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.organ);
        }

        public override string ToString()
        {
            return "GetOrganResponse: " +
            "\norgan: " + organ.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
