//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SofaSurgical
{
    [Serializable]
    public class GetOrganRequest : Message
    {
        public const string k_RosMessageName = "sofa_surgical_msgs/GetOrgan";
        public override string RosMessageName => k_RosMessageName;


        public GetOrganRequest()
        {
        }
        public static GetOrganRequest Deserialize(MessageDeserializer deserializer) => new GetOrganRequest(deserializer);

        private GetOrganRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetOrganRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
